### ISSUE TITLE
1st week

### ISSUE THREAD

**Issue by cheesecat47** [jinkyuhan/Algo_study#1]

**Comment by cheesecat47** [comment]
https://www.acmicpc.net/problem/10773
https://www.acmicpc.net/problem/1260

**Comment by jinkyuhan** [comment]
https://www.acmicpc.net/problem/1459  --  Gready
https://www.acmicpc.net/problem/2206  -- BFS

**Comment by atg0831** [comment]
https://www.acmicpc.net/problem/1946 -- Greedy
https://www.acmicpc.net/problem/1325 -- DFS

**Comment by jinkyuhan** [comment]
https://www.acmicpc.net/problem/1922 -- MST
일단 Prim으로 풀어보기
